In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier, VotingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
diabetes = pd.read_csv("../input/diabets/diabetes.csv") #datayı okuma
df = diabetes.copy() #datanın kopyasını alma
df = df.dropna() #boş değerleri çıkartma
df.head() #ilk 5 gözlem

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.info() # genel bilgiler


In [ ]:
df["Outcome"].value_counts() # Outcome değerleri

In [ ]:
df["Outcome"].value_counts().plot.barh(); #görsel olarak bakma

In [ ]:
df.describe().T # istatistiksel bazı değerler

In [3]:
y = df["Outcome"] # bağımlı değişken
X = df.drop(["Outcome"], axis=1) # bağımsız değişken

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.30, 
                                                    random_state=42) # datayı test train olarak bölme

# Support Vector Classification

In [5]:
svm_model = SVC(random_state = 42).fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
y_pred_train = svm_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[131  20]
 [ 41  39]]
** Test Seti Doğruluk Oranı **
: 0.7359307359307359
** Train Seti Doğruluk Oranı **
: 0.7802607076350093
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       151
           1       0.66      0.49      0.56        80

    accuracy                           0.74       231
   macro avg       0.71      0.68      0.69       231
weighted avg       0.73      0.74      0.72       231



# Support Vector Machines with Linear Kernel

In [6]:
svc_model = SVC(kernel = "linear",random_state = 42).fit(X_train, y_train)
y_pred = svc_model.predict(X_test)
y_pred_train = svc_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[122  29]
 [ 30  50]]
** Test Seti Doğruluk Oranı **
: 0.7445887445887446
** Train Seti Doğruluk Oranı **
: 0.7802607076350093
              precision    recall  f1-score   support

           0       0.80      0.81      0.81       151
           1       0.63      0.62      0.63        80

    accuracy                           0.74       231
   macro avg       0.72      0.72      0.72       231
weighted avg       0.74      0.74      0.74       231



# Decision Tree Classifier

In [8]:
cart = DecisionTreeClassifier(max_depth =8, random_state = 42)
cart_model = cart.fit(X_train, y_train)
y_pred = cart_model.predict(X_test)
y_pred_train = cart_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[110  41]
 [ 26  54]]
** Test Seti Doğruluk Oranı **
: 0.70995670995671
** Train Seti Doğruluk Oranı **
: 0.9459962756052142
              precision    recall  f1-score   support

           0       0.81      0.73      0.77       151
           1       0.57      0.68      0.62        80

    accuracy                           0.71       231
   macro avg       0.69      0.70      0.69       231
weighted avg       0.73      0.71      0.71       231



# K-nearest neighbors

In [12]:
knn = KNeighborsClassifier(n_neighbors = 8, weights = 'distance',leaf_size = 39, p = 150)
knn_model = knn.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)
y_pred_train = knn_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[116  35]
 [ 34  46]]
** Test Seti Doğruluk Oranı **
: 0.7012987012987013
** Train Seti Doğruluk Oranı **
: 1.0
              precision    recall  f1-score   support

           0       0.77      0.77      0.77       151
           1       0.57      0.57      0.57        80

    accuracy                           0.70       231
   macro avg       0.67      0.67      0.67       231
weighted avg       0.70      0.70      0.70       231



# Random Forest Classifier

In [13]:
rf_model = RandomForestClassifier(random_state = 42, n_estimators=150, max_depth=9, max_leaf_nodes=9).fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
y_pred_train = rf_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[130  21]
 [ 33  47]]
** Test Seti Doğruluk Oranı **
: 0.7662337662337663
** Train Seti Doğruluk Oranı **
: 0.8212290502793296
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       151
           1       0.69      0.59      0.64        80

    accuracy                           0.77       231
   macro avg       0.74      0.72      0.73       231
weighted avg       0.76      0.77      0.76       231



# Ada Boost Classifier

In [14]:
svc = SVC(probability=True,kernel='linear')
adb_model = AdaBoostClassifier(base_estimator = svc, random_state = 42).fit(X_train, y_train)
y_pred = adb_model.predict(X_test)
y_pred_train = adb_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[151   0]
 [ 80   0]]
** Test Seti Doğruluk Oranı **
: 0.6536796536796536
** Train Seti Doğruluk Oranı **
: 0.6499068901303539
              precision    recall  f1-score   support

           0       0.65      1.00      0.79       151
           1       0.00      0.00      0.00        80

    accuracy                           0.65       231
   macro avg       0.33      0.50      0.40       231
weighted avg       0.43      0.65      0.52       231



# Bagging Classifier

In [16]:
svc = SVC(probability=True, kernel='linear')
bag_model = BaggingClassifier(base_estimator = svc, random_state = 42).fit(X_train, y_train)
y_pred = bag_model.predict(X_test)
y_pred_train = bag_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[126  25]
 [ 32  48]]
** Test Seti Doğruluk Oranı **
: 0.7532467532467533
** Train Seti Doğruluk Oranı **
: 0.7821229050279329
              precision    recall  f1-score   support

           0       0.80      0.83      0.82       151
           1       0.66      0.60      0.63        80

    accuracy                           0.75       231
   macro avg       0.73      0.72      0.72       231
weighted avg       0.75      0.75      0.75       231



# Voting Classifier

> 

In [17]:
Knn_clf = KNeighborsClassifier()
DTree_clf = DecisionTreeClassifier()
SVC_clf = SVC()
voting_clf = VotingClassifier(estimators=[('SVC', SVC_clf), ('DTree', DTree_clf), ('Knn', Knn_clf)], voting='hard')
voting_clf.fit(X_train, y_train)
eclf_model = voting_clf.fit(X_train, y_train)
y_pred = eclf_model.predict(X_test)
y_pred_train = eclf_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[124  27]
 [ 34  46]]
** Test Seti Doğruluk Oranı **
: 0.7359307359307359
** Train Seti Doğruluk Oranı **
: 0.8659217877094972
              precision    recall  f1-score   support

           0       0.78      0.82      0.80       151
           1       0.63      0.57      0.60        80

    accuracy                           0.74       231
   macro avg       0.71      0.70      0.70       231
weighted avg       0.73      0.74      0.73       231



# Yapay Sinir Ağları

In [18]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
mlpc_model = MLPClassifier(random_state = 42).fit(X_train_scaled, y_train)
y_pred = mlpc_model.predict(X_test_scaled)
y_pred_train = mlpc_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[118  33]
 [ 33  47]]
** Test Seti Doğruluk Oranı **
: 0.7142857142857143
** Train Seti Doğruluk Oranı **
: 0.3500931098696462
              precision    recall  f1-score   support

           0       0.78      0.78      0.78       151
           1       0.59      0.59      0.59        80

    accuracy                           0.71       231
   macro avg       0.68      0.68      0.68       231
weighted avg       0.71      0.71      0.71       231



# Cat Boost

In [19]:
cat_model = CatBoostClassifier(random_state = 42).fit(X_train, y_train)
y_pred = cat_model.predict(X_test)
y_pred_train = cat_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

Learning rate set to 0.0079
0:	learn: 0.6887157	total: 65.9ms	remaining: 1m 5s
1:	learn: 0.6844008	total: 67.9ms	remaining: 33.9s
2:	learn: 0.6802651	total: 69.9ms	remaining: 23.2s
3:	learn: 0.6761683	total: 71.6ms	remaining: 17.8s
4:	learn: 0.6723667	total: 73.3ms	remaining: 14.6s
5:	learn: 0.6694825	total: 75ms	remaining: 12.4s
6:	learn: 0.6655485	total: 76.9ms	remaining: 10.9s
7:	learn: 0.6621665	total: 78.5ms	remaining: 9.73s
8:	learn: 0.6578806	total: 79.9ms	remaining: 8.8s
9:	learn: 0.6537770	total: 81.4ms	remaining: 8.06s
10:	learn: 0.6495001	total: 82.9ms	remaining: 7.46s
11:	learn: 0.6458545	total: 84.6ms	remaining: 6.96s
12:	learn: 0.6426352	total: 86.4ms	remaining: 6.56s
13:	learn: 0.6389943	total: 87.9ms	remaining: 6.19s
14:	learn: 0.6350428	total: 89.4ms	remaining: 5.87s
15:	learn: 0.6316617	total: 90.9ms	remaining: 5.59s
16:	learn: 0.6275027	total: 92.5ms	remaining: 5.35s
17:	learn: 0.6234740	total: 94.1ms	remaining: 5.13s
18:	learn: 0.6200799	total: 95.5ms	remaining: 4.9

197:	learn: 0.3835364	total: 370ms	remaining: 1.5s
198:	learn: 0.3830602	total: 373ms	remaining: 1.5s
199:	learn: 0.3827907	total: 375ms	remaining: 1.5s
200:	learn: 0.3823400	total: 377ms	remaining: 1.5s
201:	learn: 0.3818672	total: 378ms	remaining: 1.49s
202:	learn: 0.3811680	total: 380ms	remaining: 1.49s
203:	learn: 0.3807736	total: 381ms	remaining: 1.49s
204:	learn: 0.3804594	total: 383ms	remaining: 1.48s
205:	learn: 0.3794685	total: 385ms	remaining: 1.48s
206:	learn: 0.3788174	total: 386ms	remaining: 1.48s
207:	learn: 0.3784865	total: 388ms	remaining: 1.48s
208:	learn: 0.3780578	total: 390ms	remaining: 1.48s
209:	learn: 0.3774616	total: 391ms	remaining: 1.47s
210:	learn: 0.3766394	total: 393ms	remaining: 1.47s
211:	learn: 0.3762569	total: 395ms	remaining: 1.47s
212:	learn: 0.3756079	total: 397ms	remaining: 1.47s
213:	learn: 0.3751530	total: 398ms	remaining: 1.46s
214:	learn: 0.3749136	total: 400ms	remaining: 1.46s
215:	learn: 0.3745000	total: 402ms	remaining: 1.46s
216:	learn: 0.37

431:	learn: 0.3031963	total: 743ms	remaining: 977ms
432:	learn: 0.3030978	total: 747ms	remaining: 978ms
433:	learn: 0.3028105	total: 748ms	remaining: 976ms
434:	learn: 0.3026108	total: 750ms	remaining: 974ms
435:	learn: 0.3022832	total: 752ms	remaining: 972ms
436:	learn: 0.3018303	total: 753ms	remaining: 970ms
437:	learn: 0.3016567	total: 755ms	remaining: 968ms
438:	learn: 0.3012808	total: 756ms	remaining: 966ms
439:	learn: 0.3010540	total: 758ms	remaining: 964ms
440:	learn: 0.3007535	total: 759ms	remaining: 962ms
441:	learn: 0.3006315	total: 760ms	remaining: 960ms
442:	learn: 0.3004195	total: 762ms	remaining: 958ms
443:	learn: 0.3001283	total: 763ms	remaining: 956ms
444:	learn: 0.2997405	total: 765ms	remaining: 954ms
445:	learn: 0.2995206	total: 766ms	remaining: 952ms
446:	learn: 0.2993545	total: 768ms	remaining: 950ms
447:	learn: 0.2991675	total: 770ms	remaining: 948ms
448:	learn: 0.2990667	total: 771ms	remaining: 946ms
449:	learn: 0.2989043	total: 773ms	remaining: 944ms
450:	learn: 

674:	learn: 0.2525106	total: 1.11s	remaining: 537ms
675:	learn: 0.2522529	total: 1.12s	remaining: 536ms
676:	learn: 0.2520385	total: 1.12s	remaining: 534ms
677:	learn: 0.2517584	total: 1.12s	remaining: 532ms
678:	learn: 0.2514919	total: 1.12s	remaining: 531ms
679:	learn: 0.2513772	total: 1.12s	remaining: 529ms
680:	learn: 0.2512158	total: 1.13s	remaining: 527ms
681:	learn: 0.2509524	total: 1.13s	remaining: 525ms
682:	learn: 0.2507112	total: 1.13s	remaining: 524ms
683:	learn: 0.2504954	total: 1.13s	remaining: 522ms
684:	learn: 0.2502927	total: 1.13s	remaining: 521ms
685:	learn: 0.2502829	total: 1.13s	remaining: 519ms
686:	learn: 0.2500950	total: 1.14s	remaining: 517ms
687:	learn: 0.2498702	total: 1.14s	remaining: 516ms
688:	learn: 0.2496716	total: 1.14s	remaining: 514ms
689:	learn: 0.2494864	total: 1.14s	remaining: 512ms
690:	learn: 0.2491940	total: 1.14s	remaining: 511ms
691:	learn: 0.2489306	total: 1.14s	remaining: 509ms
692:	learn: 0.2487406	total: 1.14s	remaining: 507ms
693:	learn: 

919:	learn: 0.2077894	total: 1.49s	remaining: 130ms
920:	learn: 0.2075037	total: 1.49s	remaining: 128ms
921:	learn: 0.2074687	total: 1.49s	remaining: 126ms
922:	learn: 0.2072346	total: 1.5s	remaining: 125ms
923:	learn: 0.2072093	total: 1.5s	remaining: 123ms
924:	learn: 0.2071061	total: 1.5s	remaining: 122ms
925:	learn: 0.2069130	total: 1.5s	remaining: 120ms
926:	learn: 0.2066739	total: 1.5s	remaining: 118ms
927:	learn: 0.2065458	total: 1.5s	remaining: 117ms
928:	learn: 0.2064307	total: 1.5s	remaining: 115ms
929:	learn: 0.2063363	total: 1.51s	remaining: 113ms
930:	learn: 0.2062561	total: 1.51s	remaining: 112ms
931:	learn: 0.2061108	total: 1.51s	remaining: 110ms
932:	learn: 0.2059370	total: 1.51s	remaining: 109ms
933:	learn: 0.2057954	total: 1.51s	remaining: 107ms
934:	learn: 0.2057084	total: 1.51s	remaining: 105ms
935:	learn: 0.2055354	total: 1.52s	remaining: 104ms
936:	learn: 0.2054403	total: 1.52s	remaining: 102ms
937:	learn: 0.2050729	total: 1.52s	remaining: 100ms
938:	learn: 0.20495

# LightGBM

In [20]:
lgbm_model = LGBMClassifier(random_state = 42).fit(X_train, y_train)
y_pred = lgbm_model.predict(X_test)
y_pred_train = lgbm_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[115  36]
 [ 27  53]]
** Test Seti Doğruluk Oranı **
: 0.7272727272727273
** Train Seti Doğruluk Oranı **
: 1.0
              precision    recall  f1-score   support

           0       0.81      0.76      0.78       151
           1       0.60      0.66      0.63        80

    accuracy                           0.73       231
   macro avg       0.70      0.71      0.71       231
weighted avg       0.74      0.73      0.73       231



# XGBM

In [21]:
xgb_model = XGBClassifier(random_state = 42).fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)
y_pred_train = xgb_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[116  35]
 [ 26  54]]
** Test Seti Doğruluk Oranı **
: 0.7359307359307359
** Train Seti Doğruluk Oranı **
: 1.0
              precision    recall  f1-score   support

           0       0.82      0.77      0.79       151
           1       0.61      0.68      0.64        80

    accuracy                           0.74       231
   macro avg       0.71      0.72      0.72       231
weighted avg       0.74      0.74      0.74       231



# Gaussian Naive Bayes

In [22]:
nb = GaussianNB()
nb_model = nb.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)
y_pred_train = nb_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[119  32]
 [ 27  53]]
** Test Seti Doğruluk Oranı **
: 0.7445887445887446
** Train Seti Doğruluk Oranı **
: 0.7672253258845437
              precision    recall  f1-score   support

           0       0.82      0.79      0.80       151
           1       0.62      0.66      0.64        80

    accuracy                           0.74       231
   macro avg       0.72      0.73      0.72       231
weighted avg       0.75      0.74      0.75       231



# GBM Model

In [23]:
gbm_model = GradientBoostingClassifier(random_state=42).fit(X_train, y_train)
y_pred = gbm_model.predict(X_test)
y_pred_train = gbm_model.predict(X_train)
print("** Karmaşıklık Matrisi **\n",confusion_matrix(y_test, y_pred))
print("** Test Seti Doğruluk Oranı **\n:",accuracy_score(y_test, y_pred))
print("** Train Seti Doğruluk Oranı **\n:",accuracy_score(y_train, y_pred_train))
print(classification_report(y_test, y_pred)) 

** Karmaşıklık Matrisi **
 [[120  31]
 [ 27  53]]
** Test Seti Doğruluk Oranı **
: 0.7489177489177489
** Train Seti Doğruluk Oranı **
: 0.9497206703910615
              precision    recall  f1-score   support

           0       0.82      0.79      0.81       151
           1       0.63      0.66      0.65        80

    accuracy                           0.75       231
   macro avg       0.72      0.73      0.73       231
weighted avg       0.75      0.75      0.75       231



# Tüm Modellerin Karşılaştırılması

In [ ]:
modeller = [
    knn_model,
    svc_model,
    nb_model,
    mlpc_model,
    cart_model,
    rf_model,
    gbm_model,
    cat_model,
    lgbm_model,
]


for model in modeller:
    isimler = model.__class__.__name__
    y_pred = model.predict(X_test)
    dogruluk = accuracy_score(y_test, y_pred)
    print("-"*28)
    print(isimler + ":" )
    print("Accuracy: {:.4%}".format(dogruluk))

In [ ]:
sonuc = []

sonuclar = pd.DataFrame(columns= ["Modeller","Accuracy"])

for model in modeller:
    isimler = model.__class__.__name__
    y_pred = model.predict(X_test)
    dogruluk = accuracy_score(y_test, y_pred)    
    sonuc = pd.DataFrame([[isimler, dogruluk*100]], columns= ["Modeller","Accuracy"])
    sonuclar = sonuclar.append(sonuc)
    
    
sns.barplot(x= 'Accuracy', y = 'Modeller', data=sonuclar, color="r")
plt.xlabel('Accuracy %')
plt.title('Modellerin Doğruluk Oranları');    